#!/usr/bin/env bash
sudo apt-get install -y python3-dev
sudo apt-get install -y libmysqlclient-dev
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y pkg-config
sudo pip3 install mysqlclient
sudo pip3 install SQLAlchemy
